# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'juegoventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(927, 508)
        Dialog.setMinimumSize(QtCore.QSize(927, 508))
        Dialog.setMaximumSize(QtCore.QSize(927, 508))
        Dialog.setSizeIncrement(QtCore.QSize(0, 0))
        Dialog.setStyleSheet("QWidget#Dialog{\n"
"background-color: qlineargradient(spread:pad, x1:0.222091, y1:0.25, x2:0.556818, y2:0.528, stop:0.551136 rgba(121, 54, 255, 255));}")
        self.parainstrulabel = QtWidgets.QLabel(Dialog)
        self.parainstrulabel.setGeometry(QtCore.QRect(0, -10, 361, 51))
        self.parainstrulabel.setStyleSheet("font: 20pt \"OCR A Extended\";\n"
"color: black;")
        self.parainstrulabel.setObjectName("parainstrulabel")
        self.empiezaboton = QtWidgets.QPushButton(Dialog)
        self.empiezaboton.setGeometry(QtCore.QRect(820, 210, 101, 41))
        self.empiezaboton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.empiezaboton.setStyleSheet("border-radius:20px;\n"
"font: 12pt \"OCR A Extended\";\n"
"background-color: rgb(59, 59, 179);\n"
"color:white;\n"
"\n"
"")
        self.empiezaboton.setObjectName("empiezaboton")
        self.Fondoventana = QtWidgets.QLabel(Dialog)
        self.Fondoventana.setGeometry(QtCore.QRect(-70, -60, 1061, 601))
        self.Fondoventana.setObjectName("Fondoventana")
        self.parapegartxt = QtWidgets.QLabel(Dialog)
        self.parapegartxt.setGeometry(QtCore.QRect(0, 30, 811, 221))
        self.parapegartxt.setMinimumSize(QtCore.QSize(0, 211))
        self.parapegartxt.setStyleSheet("font: 12pt \"OCR A Extended\";\n"
"color: black;")
        self.parapegartxt.setScaledContents(False)
        self.parapegartxt.setWordWrap(True)
        self.parapegartxt.setObjectName("parapegartxt")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(820, 260, 101, 41))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("border-radius:20px;\n"
"font: 12pt \"OCR A Extended\";\n"
"background-color: rgb(85, 255, 127);\n"
"color:white;\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.dijistetxt = QtWidgets.QLabel(Dialog)
        self.dijistetxt.setGeometry(QtCore.QRect(0, 240, 351, 41))
        self.dijistetxt.setStyleSheet("font: 20pt \"OCR A Extended\";\n"
"color: black;")
        self.dijistetxt.setObjectName("dijistetxt")
        self.parapegartxt_2 = QtWidgets.QLabel(Dialog)
        self.parapegartxt_2.setGeometry(QtCore.QRect(0, 280, 811, 211))
        self.parapegartxt_2.setStyleSheet("font: 12pt \"OCR A Extended\";\n"
"color: black;")
        self.parapegartxt_2.setScaledContents(False)
        self.parapegartxt_2.setWordWrap(True)
        self.parapegartxt_2.setObjectName("parapegartxt_2")
        self.dijistetxt_2 = QtWidgets.QLabel(Dialog)
        self.dijistetxt_2.setGeometry(QtCore.QRect(760, 0, 71, 21))
        self.dijistetxt_2.setStyleSheet("font: 12pt \"OCR A Extended\";\n"
"color: black;")
        self.dijistetxt_2.setObjectName("dijistetxt_2")
        self.Tiempoled = QtWidgets.QLCDNumber(Dialog)
        self.Tiempoled.setGeometry(QtCore.QRect(830, 2, 91, 21))
        self.Tiempoled.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.Tiempoled.setAutoFillBackground(False)
        self.Tiempoled.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.Tiempoled.setLineWidth(1)
        self.Tiempoled.setMidLineWidth(0)
        self.Tiempoled.setMode(QtWidgets.QLCDNumber.Dec)
        self.Tiempoled.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.Tiempoled.setProperty("intValue", 0)
        self.Tiempoled.setObjectName("Tiempoled")
        self.Fondoventana.raise_()
        self.parainstrulabel.raise_()
        self.empiezaboton.raise_()
        self.parapegartxt.raise_()
        self.pushButton_3.raise_()
        self.dijistetxt.raise_()
        self.parapegartxt_2.raise_()
        self.dijistetxt_2.raise_()
        self.Tiempoled.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.parainstrulabel.setText(_translate("Dialog", "Lee el siguiente texto:"))
        self.empiezaboton.setText(_translate("Dialog", "Empezar"))
        self.Fondoventana.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/cct/DALL·E 2023-02-19 05.17.40 - Fondo de IA diseño.png\"/></p></body></html>"))
        self.parapegartxt.setText(_translate("Dialog", "Entre las ideas que, a 500 años, se tienen sobre cómo sucedió la Conquista de México, se encuentra la identificación de Hernán Cortés con Quetzalcóatl y el debate sobre si los indígenas, en particular los mexicas, concibieron a todos los españoles como dioses. Esta segunda temática ha sido objeto de apasionadas discusiones, especialmente a partir del análisis de la palabra , que fue la que los nahuas utilizaron para calificar a los españoles; una palabra que, si bien se puede traducir por “dios” en ciertos contextos, también transmitía otros significados según las circunstancias. En cuanto a si Cortés fue considerado un dios específico, de hecho, uno de los más importantes del panteón náhuatl, eso es Quetzalcóatl mismo, numerosas fuentes históricas sugieren que efectivamente así fue. Pero, ¿quién era Quetzalcóatl para los mexicas en 1519 y por qué relacionaron al recién llegado, venido del mar y desembarcado en el borde oriental de la tierra conocida, con esta divinidad?"))
        self.pushButton_3.setText(_translate("Dialog", "Reiniciar"))
        self.dijistetxt.setText(_translate("Dialog", "Dale click a empezar"))
        self.parapegartxt_2.setText(_translate("Dialog", "<html><head/><body><p align=\"justify\"><br/></p></body></html>"))
        self.dijistetxt_2.setText(_translate("Dialog", "Tiempo:"))
import fondo_rc
